# Generated by Django 4.1.4 on 2022-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
