# Generated by Django 4.1.4 on 2022-12-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(default=1, upload_to="\\image"),
            preserve_default=False,
        ),
    ]
